### entry point for the script
get http://localhost:3001/

###
get http://localhost:3001/api/users

###
post http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "juanfri ",
  "surName": "losa",
  "email": "ayelo@ayelo.com",
  "password": "1122",
  "phone": "+34 6677746663",
  "address": "calle mayor"
}

