version: '3'
services:
  api:
    stdin_open: true
    tty: true
    build: .
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      DATABASE_NAME: '${DATABASE_NAME}'
      DATABASE_USERNAME: '${DATABASE_USERNAME}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
    command: sh -c "yarn migrate && yarn start"
  db:
    image: postgres:13.6-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
