version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_NAME: '${DATABASE_NAME}'
      DATABASE_USERNAME: '${DATABASE_USERNAME}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
    command: sh -c 'yarn migrate && yarn dev'
  postgres:
    image: postgres:13.6-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: '${DATABASE_USERNAME}'
      POSTGRES_DB: '${DATABASE_NAME}'
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
