version: '3'
services:
  api:
    build: .
    command: yarn migrate
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      DATABASE_NAME: a-team-postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123456
  db:
    image: postgres:13.6-alpine3.15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: a-team-postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
